# Generated by Django 4.0.3 on 2024-07-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lkstatuscode',
            fields=[
                ('lk_status_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lk_status_name', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_for', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('lk_status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lkstatuscode')),
            ],
        ),
    ]
